UXFCP-3645 (fix): Removed wrong assets url from notification user_note
Wikia/reverb-ext pull request #28
Opened 2023-04-21 09:35 UTC by pawelswiszcz

## Links
[UXFCP-3645](https://fandom.atlassian.net/browse/UXFCP-3645)

## Description
**Why**: Cheevos images are displayed as broken in notifications panel for gamepedia wikis. The Cheevos image URL is with `/v2/` what is wrong. 

**How**: The assets should not have `/v2/` url, so I've removed the fixing pattern in filter

## Who might be interested
UXFCP
## Testing Recommendations
- [ ] Check Notification site for gamepedia wiki `https://[wiki]/wiki/Special:Notifications` the cheevos should be visible 
- [ ] Check Notification box on global nav for gamepedia wiki. The cheevos should be visible

<details><summary>screenshot</summary>
<p>

![Zrzut ekranu 2023-04-21 o 10 00 13](https://user-images.githubusercontent.com/1814271/233592396-40fac19e-8fd6-4269-9ef8-1d3fc6e28e6d.png)

</p>
</details>

2023-04-24 05:21 UTC, sSwiergosz commented
**issue**: @pawelswiszcz are you sure this is a proper solution? When I'm accessing gp notifications on production I see that they're working correctly, an achievement is showing, and **it has** `v2` in the path:
- URL: http://community.fandom.com/extensions-ucp/v2/Cheevos/images/gp30.png
![Screenshot 2023-04-24 at 07 18 10](https://user-images.githubusercontent.com/18450225/233906090-8552d0a4-854f-4a3a-9d13-6538644ad6fa.png)

I'm not sure that removing `v2` is the solution here. Additionally, when you look at the ticket's description, there are two links, working and not working, and both have `v2` in the path.

2023-04-24 05:22 UTC, sSwiergosz requested changes
Let's wait with this PR until `v2` in the path will be discussed.

2023-04-24 07:39 UTC, wera-trollcode commented
Just a note after testing if this works properly and merging this to REL1_39, the REL1_39 should be merged back to master.

2023-04-25 06:02 UTC, wera-trollcode approved these changes

2023-04-25 06:06 UTC, sSwiergosz approved these changes

2023-05-15 13:15 UTC, sSwiergosz approved these changes

2023-05-15 13:43 UTC, merged